version: "3.0"
services:
  web:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    working_dir: /home/dynamodblocal
    image: amazon/dynamodb-local:latest
    ports:
      - 8000:8000
    volumes:
      - vh-data:/home/dynamodblocal/data
    user: root

volumes:
  vh-data:
