version: "3"
services:
  veganhacktivists:
    depends_on:
      - db
    build:
      context: .
      args:
        - CF_SPACE_ID=$CF_SPACE_ID
        - CF_DELIVERY_ACCESS_TOKEN=$CF_DELIVERY_ACCESS_TOKEN
        - CF_PREVIEW_ACCESS_TOKEN=$CF_PREVIEW_ACCESS_TOKEN
        - CF_ENVIRONMENT=$CF_ENVIRONMENT
    environment:
      - DATABASE_URL=postgresql://vegan_hacktivists:localpass@db:5432/vegan_hacktivists?schema=public
    ports:
      - 3000:3000
  db:
    from: postgres:14
    environment:
      POSTGRES_USER: vegan_hacktivists
      POSTGRES_PASSWORD: localpass
      POSTGRES_DB: vegan_hacktivists
